version: "3.2"
services:
  app:
    build: .
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=testuser
      - DATABASE_NAME=testdb
      - DATABASE_PASSWORD=testpassword
      - DATABASE_PORT=3306
  mysql:
    image: "mysql:5.7.14"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testpassword
      - MYSQL_DATABASE=testdb
